reastaurant_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('  /', include('manager.urls')),
    path('rest_admin/', include('rest_admin.urls')),
    path('waiter/', include('waiter.urls')),
    path('kitchen/', include('kitchen.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('webpush/', include('webpush.urls')),
    path("__debug__/", include("debug_toolbar.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# User Panel URL = http://127.0.0.1:8000/restaurant/menu/2/1/

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu_demo/<int:id>/<int:pk>/', views.demo, name='demo'),
    path('menu/<int:id>/<int:pk>/', views.menu_list, name='menu'),
    path('add_to_cart_ajax/', views.add_to_cart_ajax, name='add_to_cart_ajax'),
    path('add_to_cart/<int:id>/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:id>/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_s_from_cart/<int:id>/<int:pk>/', views.remove_single_item_from_cart, name='remove_single'),
    path('order_summary/<int:id>/<int:id2>/', views.order_summary, name='order_summary'),
    path('place_order/<int:id>/<int:id2>/', views.proceed_to_pay, name='place_order'),
    path('call_waiter/<int:id>/', views.call_a_waiter, name='call_waiter'),
    path('com/<int:id>/', views.comment, name='com'),
    path('add_to_cart_order/<int:id>/<int:pk>/', views.add_to_cart_order, name='add_to_cart_order'),
    path('remove_from_cart_order/<int:id>/<int:pk>/', views.remove_single_item_from_cart_order, name='remove_from_cart_order'),
    path('demo/<int:id>/<int:pk>/', views.demo, )

] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

waiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'waiter'

urlpatterns = [
    path('', views.table_view, name='table_view'),
    path('manual_order/<int:id>/', views.manual_order, name='manual_order'),
    path('t_orders/', views.today_order, name='t_order'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/customer/menu.html
<!DOCTYPE html>
{% load static %}
{% load webpush_notifications %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <link
      href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'my_css/menu.css' %}" />
    {% webpush_header %}
    <title>Menu</title>
  </head>

  <body>
    <section class="navigation">
      <nav
        class="navbar shadow navbar-expand-lg navbar-light bg-light"
        style="
          background-color: #fff2d9 !important;
          border-bottom-left-radius: 30px;
          border-bottom-right-radius: 30px;
        "
      >
        <div class="container pb-4 pb-md-0">
          <a class="navbar-brand text-uppercase mb-4 mb-md-0" href="#"
            ><span style="color: black; font-weight: 500"
              >{{ table.rest.restaurant_name|capfirst }}</span
            ></a
          >
          <p class="d-md-none">What do you want to have today ?</p>
          <form class="d-flex ms-auto w-100">
            <input
              class="form-control form-control-sm me-2 p-2"
              type="search"
              placeholder="{{ table.rest.restaurant_name|capfirst }}"
              aria-label="Search"
            />
            <button class="btn btn-sm" type="submit">
              <i class="material-icons" style="font-size: 20px; color: white"
                >search</i
              >
            </button>
          </form>
        </div>
      </nav>
    </section>

    <section class="category mt-4 mt-md-0 mb-4 mb-md-0">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        {% for i in cat %}
        <li class="nav-item" role="presentation">
          <button
            class="nav-link {% if forloop.counter == 1 %}active{% endif %}"
            id="pills-{{ i.id }}-tab"
            data-bs-toggle="pill"
            data-bs-target="#pills-{{ i.id }}"
            type="button"
            role="tab"
            aria-controls="pills-{{ i.id }}"
            aria-selected="{% if forloop.counter == 1 %}true{% endif %}"
          >
            <i class="material-icons" 
                >lunch_dining</i
              >
          </button>
          {{ i.Category_Name }}
        </li>
        {% endfor %}
      </ul>

      <div class="tab-content" id="pills-tabContent">
        {% for j in cat %}
        <div
          class="tab-pane fade{% if forloop.counter == 1 %} show active{% endif %} p-2"
          id="pills-{{ j.id }}"
          role="tabpanel"
          aria-labelledby="pills-{{ j.id }}-tab"
        >
          {% for i in menu %} 
            {% if j.Category_Name == i.category.Category_Name %} 
              <div class="card float-left">
                <div class="row ">
                  <div class="col-5">
                    <img class="card-img-top h-100" src="{{ i.Dish_image.url }}" alt="">
                  </div>
                  <div class="col-5">
                    <div class="card-block p-2">
                      <h6 class="card-title" style="margin-bottom: .2rem;">{{ i.Dish_Name }}</h6>
                      <p class="card-text" style="margin-bottom: .2rem;">{{ i.Dish_Description|truncatechars:15 }}</p>
                      <p class="card-text" style="margin-bottom: .2rem;"><span class="" >₹ </span>{{ i.Price }}</p>
                    </div>
                  </div>
                  <div class="col-2 ">
                    <a
                      style="text-decoration: none; display: block;"
                      href="{% url 'restaurant:remove_single' i.id table.id %}"
                    >
                      <i class="material-icons" style="color:white; background-color:#3b9a75; margin-top:10px; border-radius: 5px">remove</i>
                    </a>
                    {% spaceless %}
                    <a class="card-text quan status p-1"  style="color:black; text-decoration:none; font-weight:bold; display: block;">
                    {% for j in cart %} 
                        {% if j.product.id == i.id %}       
                            {{ j.quantity }}
                      {% endif %}
                  {% endfor %}
                   </a>
                   {% endspaceless %}

                    <a
                      class="plus"
                      style="text-decoration: none; display: block;"
                      href="{% url 'restaurant:add_to_cart' i.id table.id %}"
                    >
                      <i class="material-icons" style="color:white; background-color:#3b9a75; margin-top:10px; border-radius: 5px"
                      >add</i>
                    </a>
                  </div>
                </div>
              </div>
            {% endif %} 
          {% endfor %}
        </div>
        {% endfor %}
    </section>

    <section class="footer mt-5">
      <nav class="nav">
        <a href="{% url 'restaurant:menu' table.rest.id table.table_no %}" class="nav__link nav__link--active">
          <i class="material-icons nav__icon">menu_book</i>
          <span class="nav__text">MENU</span>
        </a>
        <a href="{% url 'restaurant:order_summary' table.rest.id table.table_no %}" class="nav__link ">
          <i class="material-icons nav__icon">shopping_cart</i>
          <span class="nav__text">MY ORDERS</span>
        </a>
        <a href="#" data-catid="{{ table.id }}" class="nav__link c_wait">
          <i class="material-icons nav__icon">notifications_active</i>
          <span class="nav__text">CALL A WAITER </span>
          
        </a>

      </nav>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <script type="text/javascript">
        $(".c_wait").click(function () {
          var catid;
          catid = $(this).attr("data-catid");
          $.ajax({
            type: "GET",
            url: "{% url 'restaurant:call_waiter' table.id %}",
            data: {},
            success: function (data) {},
          });
        });
      </script>
    </section>
    <!-- javascript added -->


    <script>
      let qw = document.getElementsByClassName('quan');
      for (i=0;1<qw.length;i++){
        if(qw[i].innerText.length===0){
          qw[i].innerText += 0
        }
      }
    </script>
    <script>
      var rest_id = '{{ table.rest.id }}'

      var socket = new WebSocket('ws://localhost:8000/ws/waiter_call/'+rest_id)

      socket.onopen = function(e){
        console.log('websocket conneted user...',e)
      }

      socket.onmessage = function(e){
        console.log('websocket message user...', e)
      }

      socket.onclose = function(e) {
        
      }
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/customer/order_sumery.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <link
      href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'my_css/order_summary.css' %}" />




    <title>Scan N Order</title>
  </head>
  <body>
    <section class="navigation">
      <nav
        class="navbar shadow navbar-expand-lg navbar-light bg-light"
        style="
          background-color: #fff2d9 !important;
          border-bottom-left-radius: 30px;
          border-bottom-right-radius: 30px;
        "
      >
        <div class="container pb-md-0">
          <a class="navbar-brand text-uppercase mb-4 mb-md-0" href="#"
            ><span style="color: black; font-weight: 500"
              >{{ table.rest.restaurant_name|capfirst }}</span
            ></a
          >
        </div>
      </nav>
    </section>

    <section class="product p-4">
      {% if orders %}
      <div class="row">
        {% for i in orders.item.all %}

        <div class="card float-left">
          <div class="row">
            <div class="col-5">
              <img
                class="card-img-top h-100"
                src="{{ i.product.Dish_image.url }}"
                alt=""
              />
            </div>
            <div class="col-5">
              <div class="card-block p-2">
                <h6 class="card-title" style="margin-bottom: 0.2rem">
                  {{ i.product.Dish_Name }}
                </h6>
                <p class="card-text" style="margin-bottom: 0.2rem">
                  {{ i.product.Dish_Description|truncatechars:15 }}
                </p>

                <p class="text-dark">
                  <b>
                    <span class="" style="color: #3b9a75">₹</span>{{ i.product.Price }} * {{ i.quantity }} =
                    <span class="" style="color: #3b9a75">₹</span> {{ i.get_total_item_price }}</b
                  >
                </p>
              </div>
            </div>
            <div class="col-2">
              <a
                style="text-decoration: none; display: block"
                href="{% url 'restaurant:remove_from_cart_order' i.product.id table.id %}"
              >
                <i
                  class="material-icons"
                  style="
                    color: white;
                    background-color: #3b9a75;
                    margin-top: 10px;
                    border-radius: 5px;
                  "
                  >remove</i
                >
              </a>

              <a
                class="card-text quan status p-1"
                style="
                  color: black;
                  text-decoration: none;
                  font-weight: bold;
                  display: block;
                "
              >
                {{ i.quantity }}
              </a>

              <a
                class="plus"
                style="text-decoration: none; display: block"
                href="{% url 'restaurant:add_to_cart_order' i.product.id table.id %}"
              >
                <i
                  class="material-icons"
                  style="
                    color: white;
                    background-color: #3b9a75;
                    margin-top: 10px;
                    border-radius: 5px;
                  "
                  >add</i
                >
              </a>
            </div>
          </div>
        </div>

        {% endfor %}
      </div>

      {% endif %}
    </section>
    <section class="foot p-2">
      <div class="text-right foot container p-3">
      Sub Total: <span class="" style="color: #3b9a75">₹</span>{{ orders.get_total }}<br />
      SGST {{ orders.table_no.rest.SGST }}%: {{ orders.sgst_price }}<br />
      CGST {{ orders.table_no.rest.CGST }}%: {{ orders.cgst_price }}<br />
      <hr />
      Total: {{ orders.sc_total }}
      <hr />
      Discount {{ orders.table_no.rest.discount }}
      <hr />
      Grand Total: <span class="" style="color: #3b9a75">₹</span>{{ orders.gst_total }}<br />
      <a href="{% url 'restaurant:place_order' table.rest.id table.table_no %}"
        ><button
          class="btn btn-outline-success col-12"
          style="background-color: white; color: #3b9a75; font-size: large"
        >
          <b>Place Order</b>
        </button></a
      >
      </div>
    </section>
    <br />
    <section class="footer mt-5">
      <nav class="nav">
        <a href="{% url 'restaurant:menu' table.rest.id table.table_no %}" class="nav__link">
          <i class="material-icons nav__icon">menu_book</i>
          <span class="nav__text">MENU</span>
        </a>
        <a
          href="{% url 'restaurant:order_summary' table.rest.id table.table_no %}"
          class="nav__link nav__link--active"
        >
          <i class="material-icons nav__icon">shopping_cart</i>
          <span class="nav__text">MY ORDERS</span>
        </a>
        <a href="{% url 'restaurant:call_waiter' table.id %}" class="nav__link">
          <i class="material-icons nav__icon">notifications_active</i>
          <span class="nav__text">CALL A WAITER</span>
          
        </a>
        
      </nav>
    </section>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

templates/customer/ordersummary.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title> Shoping Cart Design Using Bootstrap 4.0 </title>
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'my_css/custom.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body class="">
	<div class="container main-section">
		<div class="row">
         <center>

			<div class="col-lg-8 pl-3 pt-3">
				<table class="table table-hover border bg-white">
				    <thead>
				      	<tr>
					        <th>Product Image</th>
                            <th>Product Name</th>
					        <th>Price</th>
					        <th style="width:10%;">Quantity</th>
					        <th>Subtotal</th>
					        <th>Action</th>
				      	</tr>
				    </thead>
				    <tbody>
				      	{% for i in orders.item.all %}
				      	<tr>
					        <td>

									<div class=" Product-img">
										<img src="{{ i.product.Dish_image.url }}" alt="..." class="img-responsive"/>
									</div>


					        </td>
                            <td>
                                <div class="">
                                            <h4 class="nomargin">{{ i.product.Dish_Name }}</h4>
                                            <p>{{ i.product.Dish_Description }}</p>
                                </div>
                            </td>
					        <td> {{ i.product.Price }} </td>
					        <td data-th="Quantity">
								<input type="number" class="form-control text-center" value="{{ i.quantity }}">
							</td>
							<td> {{ i.get_total_item_price }}</td>
					        <td class="actions" data-th="" style="width:10%;">

								<button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
							</td>
				      	</tr>
                    {% endfor %}
				    </tbody>
				    <tfoot>
						<tr>
							<td><a href="#" class="btn btn-warning text-white"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
							<td colspan="2" class="hidden-xs"></td>
							<td class="hidden-xs text-center" style="width:10%;"><strong>Discount:{{ orders.table_no.rest.discount }}<br>
                                Total : {{ orders.get_total }}</strong></td>
							<td><a href="#" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
						</tr>
					</tfoot>
				</table>
			</div>
        </center>
		</div>

	</div>


<nav class="nav">
  <a href="{% url 'restaurant:menu' table.rest.id  table.table_no %}" class="nav__link">
    <i class="material-icons nav__icon">dashboard</i>
    <span class="nav__text">Menu</span>
  </a>
  <a href="#" class="nav__link nav__link--active">
    <i class="material-icons nav__icon">person</i>
    <span class="nav__text">My Orders</span>
  </a>
  <a href="#" class="nav__link">
    <i class="material-icons nav__icon">devices</i>
    <span class="nav__text">Call A Waiter</span>
  </a>

</nav>
</body>
</html>

templates/customer/place_s.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
successfully placed
</body>
</html>