accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.r_register, name="register"),
    path('', views.user_login, name='login'),
    path('user_logout/', views.user_logout, name='user_logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'kitchen'

urlpatterns = [

    path('', views.table_view, name='table_view'),
    path('cat_list/', views.category_list, name='cat_list'),
    path('menu_list', views.menu_list, name='menu_list'),
    path('orders/', views.orders, name='orders'),
    path('t_orders/', views.today_order, name='t_order'),
    path('orders_det/<int:id>/', views.order_details, name='order_det'),
    path('P_state/<int:id>/', views.status_preparing, name='p_state'),
    path('rts_state/<int:id>/', views.status_ready_to_serve, name='rts_state'),
    path('add_menu/', views.add_menu, name='add_menu'),
    path('add_category/', views.add_categories, name='add_category'),
    path('user_d/', views.user_info, name='user_d'),
    path('menu_state/<int:id>/', views.menu_state, name='menu_state'),
    path('parcel_P_state/<int:id>/', views.parcel_status_preparing, name='parcel_p_state'),
    path('parcel_rts_state/<int:id>/', views.parcel_status_ready_to_serve, name='parcel_rts_state'),
    


] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'manager'

urlpatterns = [
    path('qr/', views.qr, name='qr'),
    path('add_menu/', views.add_menu, name='add_menu'),
    path('add_category/', views.add_categories, name='add_category'),
    path('cat_list/', views.category_list, name='cat_list'),
    path('menu_list/', views.menu_list, name='menu_list'),
    path('menu_state/<int:id>/', views.menu_avc, name='menu_state'),
    path('edit_cat/<int:id>/', views.cat_form_edit, name='edit_cat'),
    path('delete_cat/<int:id>/', views.delete, name='delete_cat'),
    path('edit_menu/<int:id>/', views.menu_form_edit, name='edit_menu'),
    path('delete_menu/<int:id>/', views.menu_delete, name='delete_menu'),
    path('orders/', views.orders, name='orders'),
    path('t_orders/', views.today_order, name='t_order'),
    path('orders_det/<int:id>/', views.order_details, name='order_det'),
    path('complete/<int:id>/', views.order_complete, name='order_complete'),
    path('pdf/<int:id>/', views.GeneratePdf.as_view(), name='pdf'),
    path('menu_state/<int:id>/', views.menu_avc, name='menu_state'),
    path('user_profile/', views.user_details, name='user_profile'),
    path('update_u/<int:id>/', views.update_details, name='update_u'),

    path('', views.table_view, name='table_view'),
    path('edit_table/<int:id>/', views.table_edit, name='edit_table'),
    path('delete_table/<int:id>/', views.table_delete, name='delete_table'),

    path('table_list/', views.table_list, name='table_list'),
    path('com_u/<int:id>/', views.com_edit, name='com_u'),
    path('manual_order/<int:id>/', views.manual_order, name='manual_order'),
    path('add_customer', views.add_customer, name='add_customer'),
    path('manual_order_parcel/', views.manual_order_parcel, name='manual_order_parcel'),
    path('parcel_pdf/<int:id>/', views.Parcel_GeneratePdf.as_view(), name='parcel_pdf'),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reastaurant_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('  /', include('manager.urls')),
    path('rest_admin/', include('rest_admin.urls')),
    path('waiter/', include('waiter.urls')),
    path('kitchen/', include('kitchen.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('webpush/', include('webpush.urls')),
    path("__debug__/", include("debug_toolbar.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# User Panel URL = http://127.0.0.1:8000/restaurant/menu/2/1/

waiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'waiter'

urlpatterns = [
    path('', views.table_view, name='table_view'),
    path('manual_order/<int:id>/', views.manual_order, name='manual_order'),
    path('t_orders/', views.today_order, name='t_order'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/charts.html
<script>

  var config = {
    type: 'doughnut',
    data: {
      datasets: [{
        data: [{{final_earn}}, {{final_Expense}}],
    backgroundColor: [
      '#ff6384', '#ffcd56'
    ],
    label: 'Population'
        }],
  labels: ['TOTAL EARN','FNIAL EXPENSE']
      },
  options: {
    responsive: true
  }
    };

  window.onload = function () {
    var ctx = document.getElementById('pie-chart').getContext('2d');
    window.myPie = new Chart(ctx, config);
  };
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<canvas id="myChart"></canvas>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

  $(document).ready(function () {
    new Chart(document.getElementById("myChart").getContext("2d"), {
      type: "bar",
      data: {
        labels: ["jan", "feb"],
        datasets: [
          {
            backgroundColor: ["#673AB7", "#90A4AE"],
            fillColor: "#000000",
            data: [{{ final_Expense }}, {{ final_earn }}]
    },
      {
        backgroundColor: ["#E1BEE7", "#0D47A1"],
        data: [{{ final_Expense }}, {{ final_earn }}]
              },

            ]
          },
    options: {
    legend: {
      display: false
    },
    scales: {
      xAxes: [{
        stacked: true
      }],
      yAxes: [{
        stacked: true
      }],
    }
  }
        });
  });
</script>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'my_css/index.css' %}">
    <title>Title</title>
</head>
<body>
<section class="section1">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="#">Features</a>
      <a class="nav-link" href="#">Pricing</a>
      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </div>
  </div>
</nav>
</section>
<section class="main">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/res1.jpg' %}" style="width: 100%; height: 50%"  class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/res2.jpg' %}" style="width: 100%; height: 50%" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/res3.jpg' %}" style="width: 100%; height: 50%" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</section>



<script src="{% static 'extra js/jquery-3.5.1.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
<script src="{% static 'extra js/jquery.counterup.min.js' %}"></script>
<script rel="script" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script rel="script" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
<script rel="script" src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script rel="script" src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>

</body>
</html>

templates/k_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
    
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <title>Waiter Dashboard</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="d-flex" id="main-wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom" >{% block res_name %}{{ restro.restaurant_name }}{% endblock %}</div>
            <div class="list-group list-group-flush my-3">
                <a href="{% url 'kitchen:t_order' %}" class="list-group-item list-group-item-action bg-transparent second-text active" >
                    <span class="me-3 mt-4"
                    ><i class="material-icons">dashboard</i></span
                    >
                    <span>Today's Order</span>
                </a>


                                <div>
                    <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" data-bs-toggle="collapse" href="#categorycollapse" role="button" aria-expanded="false" aria-controls="categorycollapse">
                        <span class="me-3"><i class="material-icons">category</i></span>
                        <span>CATEGORIES</span>
                    </a>

                    <div class="collapse px-2 py-2" id="categorycollapse">
                        <a href="{% url 'kitchen:add_category' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">add_box</i></span
                            >
                            <span>ADD CATEGORIES</span></a
                            >
                        </a>

                        <a href="{% url 'kitchen:cat_list' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>MANAGE CATEGORIES</span></a
                            >
                        </a>

                    </div>
                </div>

                                <div>
                    <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" data-bs-toggle="collapse" href="#menucollapse" role="button" aria-expanded="false" aria-controls="menucollapse">
                        <span class="me-3"><i class="material-icons">restaurant_menu</i></span>
                        <span>MENU</span>
                    </a>

                    <div class="collapse px-2 py-2" id="menucollapse">
                        <a href="{% url 'kitchen:add_menu' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">add_box</i></span
                            >
                            <span>ADD MENU</span></a
                            >
                        </a>

                        <a href="{% url 'kitchen:menu_list' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>MANAGE MENU</span></a
                            >
                        </a>

                    </div>
                </div>

                <a href="{% url 'kitchen:user_d' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <span class="me-3 mt-4"
                    ><i class="material-icons">person</i></span
                    >
                    <span>User Profile</span>
                </a>

                <a href="{% url 'accounts:user_logout' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <span class="me-3 mt-4"
                    ><i class="material-icons ">power_settings_new</i></span
                    >
                    <span>Logout</span>
                </a>

            </div>
        </div>

        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="material-icons primary-text fs-4 me-3" id="menu-toggle">tune</i>
                    <h2 class="fs-2 m-0">Dashboard</h2>
                </div>


            </nav>

            <div class="container-fluid px-4">
                
                {% block body %}
                    
                {% endblock body %}
                    

            </div>
        </div>
    </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script>
        var el = document.getElementById("main-wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
        <script>
      var rest_id = "{{ restro.id }}";

      var socket = new WebSocket(
        "ws://localhost:8000/ws/waiter_call/" + rest_id
      );

      socket.onopen = function (e) {
        console.log('websocket connected Kadmin....',e);
      };

      socket.onmessage = function (e) {
        let ale = document.getElementById("demo");

        let payload = JSON.parse(e.data);

        ale.innerHTML += `
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>${payload.payload.message}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        `;
      };

      socket.onclose = function (e) {};
    </script>
</body>

</html>

templates/manager_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <title>Manager Dashboard</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="d-flex" id="main-wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom" >{% block res_name %}{{ restro.restaurant_name }}{% endblock %}</div>
            <div class="list-group list-group-flush my-3">
                <a href="{% url 'manager:table_view' %}" class="list-group-item list-group-item-action bg-transparent second-text active" >
                    <span class="me-3 mt-4"
                    ><i class="material-icons">dashboard</i></span
                    >
                    <span>Dashboard</span>
                </a>

                <div>
                    <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" data-bs-toggle="collapse" href="#ordercollapse" role="button" aria-expanded="false" aria-controls="ordercollapse">
                        <span class="me-3"><i class="material-icons">layers</i></span>
                        <span>Orders</span>
                    </a>

                    <div class="collapse px-2 py-2" id="ordercollapse">
                        <a href="{% url 'manager:t_order' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>Today's Orders</span></a
                            >
                        </a>

                        <a href="{% url 'manager:orders' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>Order List</span></a
                            >
                        </a>
                        <a href="{% url 'manager:add_customer' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>Parcel Orders</span></a
                            >
                        </a>


                    </div>
                </div>

                <div>
                    <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" data-bs-toggle="collapse" href="#tablecollapse" role="button" aria-expanded="false" aria-controls="tablecollapse">
                        <span class="me-3"><i class="material-icons">content_paste</i></span>
                        <span>TABLE</span>
                    </a>

                    <div class="collapse px-2 py-2" id="tablecollapse">
                        <a href="{% url 'manager:qr' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">add_box</i></span
                            >
                            <span>ADD TABLE</span></a
                            >
                        </a>

                        <a href="{% url 'manager:table_view' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>MANAGE TABLE</span></a
                            >
                        </a>

                        <a href="{% url 'manager:table_list' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>Table List</span></a
                            >
                        </a>
                    </div>
                </div>

                <div>
                    <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" data-bs-toggle="collapse" href="#categorycollapse" role="button" aria-expanded="false" aria-controls="categorycollapse">
                        <span class="me-3"><i class="material-icons">category</i></span>
                        <span>CATEGORIES</span>
                    </a>

                    <div class="collapse px-2 py-2" id="categorycollapse">
                        <a href="{% url 'manager:add_category' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">add_box</i></span
                            >
                            <span>ADD CATEGORIES</span></a
                            >
                        </a>

                        <a href="{% url 'manager:cat_list' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>MANAGE CATEGORIES</span></a
                            >
                        </a>

                    </div>
                </div>

                                <div>
                    <a class="list-group-item list-group-item-action bg-transparent second-text fw-bold" data-bs-toggle="collapse" href="#menucollapse" role="button" aria-expanded="false" aria-controls="menucollapse">
                        <span class="me-3"><i class="material-icons">restaurant_menu</i></span>
                        <span>MENU</span>
                    </a>

                    <div class="collapse px-2 py-2" id="menucollapse">
                        <a href="{% url 'manager:add_menu' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">add_box</i></span
                            >
                            <span>ADD MENU</span></a
                            >
                        </a>

                        <a href="{% url 'manager:menu_list' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold" >
                            <span class="me-3"
                                ><i class="material-icons">list_alt</i></span
                            >
                            <span>MANAGE MENU</span></a
                            >
                        </a>

                    </div>
                </div>

                <a href="{% url 'manager:user_profile' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <span class="me-3 mt-4"
                    ><i class="material-icons">person</i></span
                    >
                    <span>My Profile</span>
                </a>

                <a href="{% url 'accounts:user_logout' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <span class="me-3 mt-4"
                    ><i class="material-icons ">power_settings_new</i></span
                    >
                    <span>Logout</span>
                </a>

            </div>
        </div>

        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="material-icons primary-text fs-4 me-3" id="menu-toggle">tune</i>
                    <h2 class="fs-2 m-0">Dashboard</h2>
                </div>


            </nav>

            <div class="container-fluid px-4">
                <div id="demo"></div>
                {% block body %}
                    
                {% endblock body %}
                    

            </div>
        </div>
    </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script>
        var el = document.getElementById("main-wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
        <script>
      var rest_id = "{{ restro.id }}";

      var socket = new WebSocket(
        "ws://localhost:8000/ws/waiter_call/" + rest_id
      );

      socket.onopen = function (e) {
        console.log(e);
      };

      socket.onmessage = function (e) {
        let ale = document.getElementById("demo");

        let payload = JSON.parse(e.data);

        ale.innerHTML += `
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>${payload.payload.message}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        `;
      };

      socket.onclose = function (e) {};
    </script>
</body>

</html>

templates/waiter_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <link
      href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet"
    />

    <title>Waiter Dashboard</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    {% block head %} {% endblock %}
  </head>

  <body>
    <div class="d-flex" id="main-wrapper">
      <!-- Sidebar -->
      <div class="bg-white" id="sidebar">
        <div
          class="
            sidebar-heading
            text-center
            py-4
            primary-text
            fs-4
            fw-bold
            text-uppercase
            border-bottom
          "
        >
          {% block res_name %}{{ restro.restaurant_name }}{% endblock %}
        </div>
        <div class="list-group list-group-flush my-3">
          <a
            href="{% url 'waiter:table_view' %}"
            class="
              list-group-item list-group-item-action
              bg-transparent
              second-text
              active
            "
          >
            <span class="me-3 mt-4"
              ><i class="material-icons">dashboard</i></span
            >
            <span>Dashboard</span>
          </a>

          <a
            href="{% url 'waiter:t_order' %}"
            class="
              list-group-item list-group-item-action
              bg-transparent
              second-text
              fw-bold
            "
          >
            <span class="me-3 mt-4"
              ><i class="material-icons">list_alt</i></span
            >
            <span>Today's Orders</span>
          </a>

          <a
            href="{% url 'accounts:user_logout' %}"
            class="
              list-group-item list-group-item-action
              bg-transparent
              second-text
              fw-bold
            "
          >
            <span class="me-3 mt-4"
              ><i class="material-icons">power_settings_new</i></span
            >
            <span>Logout</span>
          </a>
        </div>
      </div>

      <div id="page-content-wrapper">
        <nav
          class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4"
        >
          <div class="d-flex align-items-center">
            <i class="material-icons primary-text fs-4 me-3" id="menu-toggle"
              >tune</i
            >
            <h2 class="fs-2 m-0">Dashboard</h2>
          </div>
        </nav>

        <div class="container-fluid px-4">
          <div id="demo"></div>
          {% block body %} {% endblock body %}
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script>
      var el = document.getElementById("main-wrapper");
      var toggleButton = document.getElementById("menu-toggle");

      toggleButton.onclick = function () {
        el.classList.toggle("toggled");
      };
    </script>

    <script>
      var rest_id = "{{ restro.id }}";

      var socket = new WebSocket(
        "ws://localhost:8000/ws/waiter_call/" + rest_id
      );

      socket.onopen = function (e) {
        console.log('websocket connted admin...',e);
      };

      socket.onmessage = function (e) {
        console.log('message...', e)
        let ale = document.getElementById("demo");

        let payload = JSON.parse(e.data);

        ale.innerHTML += `
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>${payload.payload.message}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        `;
      };

      socket.onclose = function (e) {};
    </script>
  </body>
</html>